ALTER SESSION SET CURRENT_SCHEMA = IFOBS;

-- Клієнти КБ у яких підключені тільки закриті рахунки
SELECT DISTINCT NICKNAME AS "Ідентифікатоп клієнта", DESCR AS "Назва клієнта", TOBOID AS "ТОБО", TOBONAME AS "Назва ТОБО" FROM ACCOUNT a JOIN
                              ( SELECT NICKNAME, CONTRAGENTBRANCHID FROM CLIENT 
                                JOIN CONTRAGENTBRANCH ON CLIENT.ID = CONTRAGENTBRANCH.CLIENTID 
                                WHERE CLIENTSTATUSID = 0) c ON a.CONTRAGENTBRANCHID = c.CONTRAGENTBRANCHID
WHERE ACCOUNTSTATEID = 2
AND ISMONITORED = 1
AND NICKNAME NOT IN 
                  ( SELECT NICKNAME FROM ACCOUNT a JOIN
                    (SELECT NICKNAME, CONTRAGENTBRANCHID FROM CLIENT 
                    JOIN CONTRAGENTBRANCH ON CLIENT.ID = CONTRAGENTBRANCH.CLIENTID 
                    WHERE CLIENTSTATUSID = 0) c ON a.CONTRAGENTBRANCHID = c.CONTRAGENTBRANCHID
                    WHERE ACCOUNTSTATEID <> 2
                    AND ISMONITORED = 1
                    GROUP BY NICKNAME)
ORDER BY TOBOID, NICKNAME; 